---
- name: Install control panel
  hosts: k8s_masters
  remote_user: "{{ user }}"
  tasks:
    - name: Init master
      become: true
      ansible.builtin.shell:
        cmd: "kubeadm init --control-plane-endpoint=$HOSTNAME"
    - name: setup admin user
      ansible.builtin.shell:
        cmd: "mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config"
    - name: Get the token for joining the worker nodes
      become: yes
      ansible.builtin.shell:
        cmd: "kubeadm token create  --print-join-command"
      register: kubernetes_join_command
    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"
    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="kubernetes_join_command" mode=0777
    - name: Install Calico
      ansible.builtin.shell:
        cmd: "kubectl apply -f https://projectcalico.docs.tigera.io/manifests/calico.yaml"
    - name: Configure kubectl alias
      ansible.builtin.lineinfile:
        path: "$HOME/.bashrc"
        search_string: "#alias l='ls -CF'"
        line: "alias k='kubectl'"
        state: present
    - name: install nfs server
      ansible.builtin.shell:
        cmd: "helm install nfs-server stable/nfs-server-provisioner"
    - name: activate autocomplete
      ansible.builtin.shell:
        cmd: "echo "source <(kubectl completion bash)" >> ~/.bashrc"


