---
- name: Install node
  hosts: k8s_nodes
  remote_user: "{{ user }}"
  tasks:
    - name: Copy join command from Ansiblehost to the worker nodes.
      become: yes
      copy:
        src: kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Join the Worker nodes to the cluster.
      become: yes
      ansible.builtin.shell:
        cmd: "sh /tmp/kubernetes_join_command"
      register: joined_or_not
